# Generated by Django 5.2.7 on 2025-10-23 13:11

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('in_stock', models.PositiveIntegerField(verbose_name='In Stock')),
                ('price', models.PositiveBigIntegerField(verbose_name='Price')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None, verbose_name='Tags')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
            ],
        ),
    ]
